### PR TITLE
Fix #199: Do not stop to replicate when producer throws exception

### LINKED ISSUE #199: Replicator does not resume once paused, due to backlog quota
#### Expected behavior

Replicator stops replication when the remote side reaches it's configured backlog quota and resumes once backlog goes below it's quota.

#### Actual behavior

Once the backlog drains, it should resume replication. Instead it stays in the paused mode. 

#### Steps to reproduce

On a global topic, allow the local backlog to grow beyond configured quota. Continue to publish messages from a remote cluster on the same topic.

#### System configuration
**Pulsar version**: 1.16

### PR DESCRIPTION
**Pull request by nkurihar**
### Motivation

This closes #199 

### Modifications

When the replication producer catches an exception,
rewind cursor and continue readMoreEntries (if possible) rather than return immediately.

An unit test for simulating #199 is also added. 

### Result

Replicator will continue to replicate even when producer exception.

### CODE REVIEW

File: pulsar-broker/src/test/java/com/yahoo/pulsar/broker/service/ReplicatorTest.java [hunk 1]
```diff
@@ -671,6 +676,70 @@ public void testReplicatorProducerClosing() throws Exception {
...
+            // Replicator for r1 -> r2
+            PersistentTopic topic = (PersistentTopic) pulsar1.getBrokerService().getTopicReference(dest.toString());
+            PersistentReplicator replicator = topic.getPersistentReplicator("r2");
+
+            // Produce 10 messages to r1, and it will be replicated to r2
+            producer1.produce(10);
+            consumer1.receive(10);
+
+            // Restrict backlog quota limit to 1
+            admin1.namespaces().setBacklogQuota("pulsar/global/ns1", new BacklogQuota(1, policy));
```
Comment (saandrews) [inline pulsar-broker/src/test/java/com/yahoo/pulsar/broker/service/ReplicatorTest.java]: Can we setup the test this way? If you want, you can create another test.
1. limit quota to 1 message
2. Publish 10 messages
3. verify receive times out after first message is received(since quota is full)
4. Increase quota to 10
5. Verify we receive the remaining 9 messages.

File: pulsar-broker/src/main/java/com/yahoo/pulsar/broker/service/persistent/PersistentReplicator.java [hunk 2]
```diff
@@ -392,15 +392,15 @@ public void sendComplete(Exception exception) {
...
                 log.error("[{}][{} -> {}] Error producing on remote broker", replicator.topicName,
                         replicator.localCluster, replicator.remoteCluster, exception);
-                return;
-            }
-
-            if (log.isDebugEnabled()) {
-                log.debug("[{}][{} -> {}] Message persisted on remote broker", replicator.topicName,
-                        replicator.localCluster, replicator.remoteCluster);
+                // cursor shoud be rewinded since it was incremented when readMoreEntries
+                replicator.cursor.rewind();
```
Comment (saandrews) [inline pulsar-broker/src/main/java/com/yahoo/pulsar/broker/service/persistent/PersistentReplicator.java]: @merlimat Do you see any side effect if we rewind it for every exception. All failed pending messages would reach here and invoke rewind.

Comment (merlimat) [inline pulsar-broker/src/main/java/com/yahoo/pulsar/broker/service/persistent/PersistentReplicator.java]: Rewind is a _cheap_ operation, it just resets the `readPosition` to `markDeletePosition + 1`

File: pulsar-broker/src/test/java/com/yahoo/pulsar/broker/service/ReplicatorTest.java (hunk 1 above)
Comment (nkurihar) [inline pulsar-broker/src/test/java/com/yahoo/pulsar/broker/service/ReplicatorTest.java]: @saandrews
I modified the test a little:
1. limit quota to 1
2. Publish 1 message and wait for reflecting backlog limitation ※
3. Publish 9 messages and verify they will be pended
※ If I produce 10 messages at once in interval of reflecting backlog limitation, they will be sended
