### PR TITLE
Fix for cursor reset after topic reload

### LINKED ISSUE #309: Fail to reset-cursor on partitioned topic
After issues with ZK #308 we are attempting to reset some consumers and we're getting the following exceptions.
How and why can a `ManagedCursorImpl` have a `ReadOnlyLedgerHandle`?

```
Caused by: com.yahoo.pulsar.broker.service.BrokerServiceException$SubscriptionInvalidCursorPosition: unable to persist position for cursor reset 730778:44020
	at com.yahoo.pulsar.broker.service.persistent.PersistentSubscription$5$1.resetFailed(PersistentSubscription.java:371)
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl$7.operationFailed(ManagedCursorImpl.java:746)
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.lambda$persistPosition$12(ManagedCursorImpl.java:1911)
	at org.apache.bookkeeper.client.ReadOnlyLedgerHandle.asyncAddEntry(ReadOnlyLedgerHandle.java:105)
	at org.apache.bookkeeper.client.ReadOnlyLedgerHandle.asyncAddEntry(ReadOnlyLedgerHandle.java:98)
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.persistPosition(ManagedCursorImpl.java:1889)
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.internalResetCursor(ManagedCursorImpl.java:768)
	at org.apache.bookkeeper.mledger.impl.ManagedCursorImpl.lambda$asyncResetCursor$4(ManagedCursorImpl.java:780)
	at org.apache.bookkeeper.mledger.util.SafeRun$1.safeRun(SafeRun.java:27)
	at org.apache.bookkeeper.util.SafeRunnable.run(SafeRunnable.java:31)
```

### PR DESCRIPTION
**Pull request by merlimat**
### Motivation

As reported in #309, the cursor reset operation will fail after a topic reload when no new mark-delete operation was issued, since the cursor ledger was set to a read-only ledger.

### Modifications

Changed the reset logic to rely on `internalAsyncMarkDelete()` which forces to create a new ledger when the cursor is in `NoLedger` state.

Fix #309

### CODE REVIEW

**Comment by merlimat** [comment]
cc @sschepens

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 1]
```diff
@@ -240,7 +240,6 @@ protected void recoverFromLedger(final ManagedCursorInfo info, final VoidCallbac
             }
 
             // Read the last entry in the ledger
-            cursorLedger = lh;
```
Comment (rdhabalia) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: so, if we don't initialize `cursorLedger` at the time recovery then it will be null initially and at that time [internal-stat](https://github.com/yahoo/pulsar/blob/master/pulsar-broker/src/main/java/com/yahoo/pulsar/broker/service/persistent/PersistentTopic.java#L1052) will not return correct value of `cursorLedgerLastEntry`. So, is there any specific reason to not initialize it at recovery time?

Comment (merlimat) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: very good point. I removed it because it is confusing to use the same variable to store 2 different kinds of ledger handler (one read-write and the other read-only)

Anyway I think it still make sense for the internal stats. In this case we would see:
```
cursorLedger = -1
cursorLedgerLastEntry = -1
```
and that is appropriate since we are in `NoLedger` state.

This below is the code that returns the `-1`:

```java
  public long getCursorLedger() {
        LedgerHandle lh = cursorLedger;
        return lh != null ? lh.getId() : -1;
    }

    public long getCursorLedgerLastEntry() {
        LedgerHandle lh = cursorLedger;
        return lh != null ? lh.getLastAddConfirmed() : -1;
    }
```

File: managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java [hunk 2]
```diff
@@ -1817,21 +1809,10 @@ public void operationFailed(ManagedLedgerException exception) {
 
     private void flushPendingMarkDeletes() {
         if (!pendingMarkDeleteOps.isEmpty()) {
-            if (RESET_CURSOR_IN_PROGRESS_UPDATER.get(this) == TRUE) {
-                failPendingMarkDeletes();
-            } else {
-                internalFlushPendingMarkDeletes();
-            }
+            internalFlushPendingMarkDeletes();
```
Comment (rdhabalia) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: `internalFlushPendingMarkDeletes` just clears previous `pendingMarkDeleteOps` and not completes the callback of `PendingMarkDeleteEntry` and there could be possibility if someone is waiting for the callback. One example [PersistentReplicator](https://github.com/yahoo/pulsar/blob/master/pulsar-broker/src/main/java/com/yahoo/pulsar/broker/service/persistent/PersistentReplicator.java#L596) waiting to just do debug-log and which is fine but just concern is that as it has callback so, one can wait on it..

Comment (merlimat) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: Actually, that is covered 😉 

Take a look at `internalMarkDelete()`, there's this code there:

```java
// Trigger the final callback after having (eventually) triggered the switchin-ledger operation. This
                // will ensure that no race condition will happen between the next mark-delete and the switching
                // operation.
                if (mdEntry.callbackGroup != null) {
                    // Trigger the callback for every request in the group
                    for (PendingMarkDeleteEntry e : mdEntry.callbackGroup) {
                        e.callback.markDeleteComplete(e.ctx);
                    }
                } else {
                    // Only trigger the callback for the current request
                    mdEntry.callback.markDeleteComplete(mdEntry.ctx);
                }
```

So, 1 single write and triggers all the callbacks

Comment (rdhabalia) [inline managed-ledger/src/main/java/org/apache/bookkeeper/mledger/impl/ManagedCursorImpl.java]: I see.
