### PR TITLE
Internal Producer/Consumer in WebSocketProxy should be closed asynchronously

### LINKED ISSUE #458: no reply from websocket proxy
#### Expected behavior
websocket proxy returns correct response.

#### Actual behavior

we execute the following script about 2 to 100 times, websocket proxy often has come to return no more response.

#### Steps to reproduce
```
# execute python script
$for i in `seq 1 1000`;do python3.5 ./websocket_produce.py;done;
create 0
create 1
create 2
create 3
create 4
create 5
create 6
create 7
create 8
create 9
=======================================================
create 0
create 2
create 3
create 4
create 5
create 6
create 7
create 9
create 8
create 1
=======================================================
・
・
#no reply
```

websocket_produce.py
```
# -*- coding:utf-8 -*-
import websocket, base64, json, sys
from multiprocessing import Pool
from multiprocessing import Process

cert = '<value>'
def create_producer(i):
    print('create '+str(i))
    return websocket.create_connection(
       'ws://<hostname>:<port>/ws/producer/persistent/prop/global/n1/topic2',  header=['cert-header-name: ' + cert])

def send_message(producer):
    s=base64.b64encode(b'abcdefg').decode('utf-8')
    message = "{\"payload\":\"" + s + "\"}"
    producer.send(message)
#    print(json.loads(producer.recv()))

p = Pool(10)
# 1. create 10 producers
producers = p.map(create_producer, range(10))
# 2. send 10messages per producer 
for i in range(10):
    p.map(send_message, producers)

print("=======================================================")
```  
    
   
   
we confirmed following when this problem occurred.
1 .  when executing ``getSession().getRemote().sendString(msg)``, suddenly ``onWebSocketError()`` is called. 
[ProducerHandler.java#L130](https://github.com/yahoo/pulsar/blob/afaa63fdaa53bc04554329b43ddbf95c5b158ae8/pulsar-websocket/src/main/java/com/yahoo/pulsar/websocket/ProducerHandler.java#L130)
[ProducerHandler.java#L114](https://github.com/yahoo/pulsar/blob/afaa63fdaa53bc04554329b43ddbf95c5b158ae8/pulsar-websocket/src/main/java/com/yahoo/pulsar/websocket/ProducerHandler.java#L114)
```
14:21:16.868 [pulsar-client-io-56-1] INFO  c.y.p.w.AbstractWebSocketHandler     - [/172.21.219.252:54150] WebSocket error on topic persistent://prop/global/n1/topic2 : null
```
2 .  and another thread calls ``onWebSocketClose()``.
```
14:21:16.876 [pulsar-web-46-15] INFO  c.y.p.w.AbstractWebSocketHandler     - [/172.21.219.252:54150] Closed WebSocket session on topic persistent://prop/global/n1/topic2. status: 1006 - reason: WebSocket Read EOF
```

3 .  after next time, request is stoped in ``ctx.writeAndFlush(request)`` and no reply from websocket proxy
[ClientCnx.java#L349](https://github.com/yahoo/pulsar/blob/029b8b09ffccad8d6021958a258d58c3ab649378/pulsar-client/src/main/java/com/yahoo/pulsar/client/impl/ClientCnx.java#L349)
  
4 .  no reply from admin API, too.
  

#### System configuration
**Pulsar version**: 1.17.2  and updated the latest version(current master) but This problem still occurred.
websocket proxy and broker run in same server.
   

Do you know what could be happening?

### PR DESCRIPTION
**Pull request by yush1ga**
This PR fixes #458.

### Motivation

- PulsarClient uses one "pulsar-client-io-*" thread in WebSocketProxy.
- onWebSocketError method is occasionally called in PulsarClient using "pulsar-client-io-\*".
- onWebSocketError calls producer/consumer close method synchronously, which uses "pulsar-client-io-\*".
- Then, the latter "pulsar-client-io-\*" thread waits and the former "pulsar-client-io-\*" will not end.

### Modifications
- Made producer/consumer closing asynchronously.

### Result
- onWebSocketError doesn't cause thread waiting.

### CODE REVIEW

File: pulsar-websocket/src/main/java/com/yahoo/pulsar/websocket/ConsumerHandler.java [hunk 1]
```diff
@@ -186,7 +186,9 @@ public void onWebSocketText(String message) {
     public void close() throws IOException {
         if (consumer != null) {
             this.service.removeConsumer(this);
-            consumer.close();
+            consumer.closeAsync().thenAccept(x ->
+                log.debug("[{}] Closed consumer asynchronously", consumer.getTopic())
```
Comment (rdhabalia) [inline pulsar-websocket/src/main/java/com/yahoo/pulsar/websocket/ConsumerHandler.java]: can we add debug statement if debug is enabled
`if (log.isDebugEnabled()) {..}`

File: pulsar-websocket/src/main/java/com/yahoo/pulsar/websocket/ProducerHandler.java [hunk 2]
```diff
@@ -83,7 +83,9 @@ public ProducerHandler(WebSocketService service, HttpServletRequest request) {
     public void close() throws IOException {
         if (producer != null) {
             this.service.removeProducer(this);
-            producer.close();
+            producer.closeAsync().thenAccept(x ->
```
Comment (rdhabalia) [inline pulsar-websocket/src/main/java/com/yahoo/pulsar/websocket/ProducerHandler.java]: should we handle if future completes with exception and we can log it.?

**Comment by merlimat** [comment]
@yush1ga @rdhabalia I just made the minor changes to the log statements, just to get it merged sooner :)
